/*
 * Copyright (C) 2021 itamar.iac
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package itamar.dirsynch.ui;

import static itamar.util.Logger.LEVEL_ERROR;
import static itamar.util.Logger.log;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author itamar.iac
 */
public class JDialogHelp extends javax.swing.JDialog {

    private final String helpFile = "DirSynch-help.html";

    /**
     * Creates new form JDialogHelp
     *
     * @param parent
     * @param modal
     */
    public JDialogHelp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            jEdtPaneHelp.setPage("file:///" + System.getProperty("user.dir") + File.separator + helpFile);
            jEdtPaneHelp.setCaretPosition(0);
            this.pack();
        } catch (IOException ex) {
            log(LEVEL_ERROR, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneHelp = new javax.swing.JScrollPane();
        jEdtPaneHelp = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPaneHelp.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPaneHelp.setPreferredSize(new java.awt.Dimension(600, 400));

        jEdtPaneHelp.setEditable(false);
        jEdtPaneHelp.setContentType("text/html"); // NOI18N
        jScrollPaneHelp.setViewportView(jEdtPaneHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEdtPaneHelp;
    private javax.swing.JScrollPane jScrollPaneHelp;
    // End of variables declaration//GEN-END:variables
}
