/*
 * MainJFrame.java
 *
 * Created on 3 de Agosto de 2006, 20:32
 */

package itamar.dirsynch;

import com.oktiva.util.FileUtil;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.ProgressMonitor;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author  Itamar Carvalho
 */
public class MainJFrame extends javax.swing.JFrame {
    private File mainDir;
    private File secDir;
    private Map mainDirMap;
    private Map secDirMap;
//    private static String defaultMainDirPath = "K:\\Ferramentas\\Equipamentos";
//    private static String defaultSecDirPath = "K:\\temp";
    private static String defaultMainDirPath = "P:\\Pessoal\\teste1";
    private static String defaultSecDirPath = "P:\\Pessoal\\teste2";
//    private static String defaultMainDirPath = "K:\\Pessoal\\java";
//    private static String defaultSecDirPath = "I:\\Pessoal\\java";
    
    private static String version = "1.3";
    private static String logFile = "DirSynch.log";
    private static boolean defaultKeep = false;
    private Map noSynchMap = null;
    private boolean firstLoad = true;
    private final String helpFile = "DirSynch-help.html";
    
    /** Creates new form MainJFrame */
    public MainJFrame() {
        initComponents();
        try {
            System.setErr(
                    new PrintStream(
                    new BufferedOutputStream(
                    new FileOutputStream(logFile))));
        } catch (FileNotFoundException ex) {
            MainJFrame.log(ex);
        }
        setTitle("DirSynch " + version);
        jTableFiles.getColumn("Sel").setMaxWidth(30);
        jTableFiles.getColumn("Main").setMaxWidth(30);
        jTableFiles.getColumn("Sec").setMaxWidth(30);
        setStatusBarText(FilePair.getLegend());
        
        ListSelectionModel rowSM = jTableFiles.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                //Ignore extra messages.
                if (e.getValueIsAdjusting()) return;
                
                ListSelectionModel lsm = (ListSelectionModel)e.getSource();
                if (lsm.isSelectionEmpty()) {
                    //System.out.println("No rows are selected.");
                    setStatusBarText(FilePair.getLegend());
                } else {
                    int selectedRow = lsm.getMinSelectionIndex();
//                    System.out.println("Row " + selectedRow
//                            + " is now selected.");
                    updateStatus();
                }
            }
        });
        
        jTxtFldMainDir.setText(defaultMainDirPath);
        jTxtFldSecDir.setText(defaultSecDirPath);
        jChkBxMenuItemKeepBackup.setSelected(defaultKeep);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jDialogHelp = new javax.swing.JDialog();
        jScrollPaneHelp = new javax.swing.JScrollPane();
        jEdtPaneHelp = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtFldSecDir = new javax.swing.JTextField();
        jTxtFldMainDir = new javax.swing.JTextField();
        statusBar = new javax.swing.JPanel();
        jLblStatusBar = new javax.swing.JLabel();
        jBtnMainDir = new javax.swing.JButton();
        jBtnSecDir = new javax.swing.JButton();
        jBtnLoad = new javax.swing.JButton();
        jBtnSynch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFiles = new javax.swing.JTable();
        jChkBoxHideEquals = new javax.swing.JCheckBox();
        jChkBoxUseHash = new javax.swing.JCheckBox();
        jMenuBarDirSynch = new javax.swing.JMenuBar();
        jMenuTools = new javax.swing.JMenu();
        jMenuSelect = new javax.swing.JMenu();
        jMenuItemAll = new javax.swing.JMenuItem();
        jMenuItemNone = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItemYesNo = new javax.swing.JMenuItem();
        jMenuItemOnlyInMain = new javax.swing.JMenuItem();
        jMenuItemOnlyInSec = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItemNewerInMain = new javax.swing.JMenuItem();
        jMenuItemNewerInSec = new javax.swing.JMenuItem();
        jMenuOptions = new javax.swing.JMenu();
        jChkBxMenuItemIncSubdirs = new javax.swing.JCheckBoxMenuItem();
        jChkBxMenuItemUseHash = new javax.swing.JCheckBoxMenuItem();
        jChkBxMenuItemHideEquals = new javax.swing.JCheckBoxMenuItem();
        jChkBxMenuItemKeepBackup = new javax.swing.JCheckBoxMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemDirSynchHelp = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jDialogHelp.setTitle("DirSynch Help");
        jDialogHelp.setAlwaysOnTop(true);
        jDialogHelp.setModal(true);
        jScrollPaneHelp.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPaneHelp.setPreferredSize(new java.awt.Dimension(600, 400));
        jEdtPaneHelp.setEditable(false);
        jEdtPaneHelp.setContentType("text/html");
        jScrollPaneHelp.setViewportView(jEdtPaneHelp);

        org.jdesktop.layout.GroupLayout jDialogHelpLayout = new org.jdesktop.layout.GroupLayout(jDialogHelp.getContentPane());
        jDialogHelp.getContentPane().setLayout(jDialogHelpLayout);
        jDialogHelpLayout.setHorizontalGroup(
            jDialogHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogHelpLayout.setVerticalGroup(
            jDialogHelpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogHelpLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DirSync");
        jLabel1.setText("Main directory:");

        jLabel2.setText("Second directory:");

        jTxtFldSecDir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 0)));
        jTxtFldSecDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFldSecDirKeyTyped(evt);
            }
        });

        jTxtFldMainDir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jTxtFldMainDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFldMainDirKeyTyped(evt);
            }
        });

        statusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        statusBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusBarMouseClicked(evt);
            }
        });

        jLblStatusBar.setText(" ");

        org.jdesktop.layout.GroupLayout statusBarLayout = new org.jdesktop.layout.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusBarLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLblStatusBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLblStatusBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jBtnMainDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dir.png")));
        jBtnMainDir.setToolTipText("Select main dir...");
        jBtnMainDir.setIconTextGap(0);
        jBtnMainDir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBtnMainDir.setMinimumSize(new java.awt.Dimension(20, 20));
        jBtnMainDir.setName("jBtnMainDir");
        jBtnMainDir.setPreferredSize(new java.awt.Dimension(20, 20));
        jBtnMainDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMainDirActionPerformed(evt);
            }
        });

        jBtnSecDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dir.png")));
        jBtnSecDir.setToolTipText("Select second dir...");
        jBtnSecDir.setIconTextGap(0);
        jBtnSecDir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBtnSecDir.setMinimumSize(new java.awt.Dimension(20, 20));
        jBtnSecDir.setName("jBtnSecDir");
        jBtnSecDir.setPreferredSize(new java.awt.Dimension(20, 20));
        jBtnSecDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSecDirActionPerformed(evt);
            }
        });

        jBtnLoad.setText("Load");
        jBtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoadActionPerformed(evt);
            }
        });

        jBtnSynch.setText("Synchronize");
        jBtnSynch.setEnabled(false);
        jBtnSynch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSynchActionPerformed(evt);
            }
        });

        jTableFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableFiles.setModel(new FileVOTableModel(
            new Object [][] {
                {new Boolean(false), null, null, null}
            },
            new String [] {
                "Sel", "Main", "Sec", "File"
            }
        ));
        jTableFiles.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTableFiles);

        jChkBoxHideEquals.setText("Hide equals");
        jChkBoxHideEquals.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChkBoxHideEquals.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jChkBoxHideEquals.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jChkBoxHideEqualsItemStateChanged(evt);
            }
        });

        jChkBoxUseHash.setText("Use hash");
        jChkBoxUseHash.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChkBoxUseHash.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jChkBoxUseHash.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jChkBoxUseHashItemStateChanged(evt);
            }
        });

        jMenuTools.setText("Tools");
        jMenuSelect.setText("Select");
        jMenuItemAll.setText("All");
        jMenuItemAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAllActionPerformed(evt);
            }
        });

        jMenuSelect.add(jMenuItemAll);

        jMenuItemNone.setText("None");
        jMenuItemNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNoneActionPerformed(evt);
            }
        });

        jMenuSelect.add(jMenuItemNone);

        jMenuSelect.add(jSeparator1);

        jMenuItemYesNo.setText("Only YES/no");
        jMenuItemYesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemYesNoActionPerformed(evt);
            }
        });

        jMenuSelect.add(jMenuItemYesNo);

        jMenuItemOnlyInMain.setText("Only in main dir");
        jMenuItemOnlyInMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOnlyInMainActionPerformed(evt);
            }
        });

        jMenuSelect.add(jMenuItemOnlyInMain);

        jMenuItemOnlyInSec.setText("Only in sec dir");
        jMenuItemOnlyInSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOnlyInSecActionPerformed(evt);
            }
        });

        jMenuSelect.add(jMenuItemOnlyInSec);

        jMenuSelect.add(jSeparator2);

        jMenuItemNewerInMain.setText("Newer in main");
        jMenuItemNewerInMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewerInMainActionPerformed(evt);
            }
        });

        jMenuSelect.add(jMenuItemNewerInMain);

        jMenuItemNewerInSec.setText("Newer in sec");
        jMenuItemNewerInSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewerInSecActionPerformed(evt);
            }
        });

        jMenuSelect.add(jMenuItemNewerInSec);

        jMenuTools.add(jMenuSelect);

        jMenuBarDirSynch.add(jMenuTools);

        jMenuOptions.setText("Options");
        jChkBxMenuItemIncSubdirs.setSelected(true);
        jChkBxMenuItemIncSubdirs.setText("Include subdirs");
        jChkBxMenuItemIncSubdirs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jChkBxMenuItemIncSubdirsItemStateChanged(evt);
            }
        });

        jMenuOptions.add(jChkBxMenuItemIncSubdirs);

        jChkBxMenuItemUseHash.setText("Use hash");
        jChkBxMenuItemUseHash.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jChkBxMenuItemUseHashItemStateChanged(evt);
            }
        });

        jMenuOptions.add(jChkBxMenuItemUseHash);

        jChkBxMenuItemHideEquals.setText("Hide equals");
        jChkBxMenuItemHideEquals.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jChkBxMenuItemHideEqualsStateChanged(evt);
            }
        });

        jMenuOptions.add(jChkBxMenuItemHideEquals);

        jChkBxMenuItemKeepBackup.setText("Keep backup");
        jMenuOptions.add(jChkBxMenuItemKeepBackup);

        jMenuBarDirSynch.add(jMenuOptions);

        jMenuHelp.setText("Help");
        jMenuItemDirSynchHelp.setText("DirSynch Help");
        jMenuItemDirSynchHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDirSynchHelpActionPerformed(evt);
            }
        });

        jMenuHelp.add(jMenuItemDirSynchHelp);

        jMenuItemAbout.setText("About...");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });

        jMenuHelp.add(jMenuItemAbout);

        jMenuBarDirSynch.add(jMenuHelp);

        setJMenuBar(jMenuBarDirSynch);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jTxtFldMainDir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jBtnMainDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jTxtFldSecDir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jBtnSecDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(statusBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jBtnLoad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnSynch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 120, Short.MAX_VALUE)
                        .add(jChkBoxUseHash)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jChkBoxHideEquals)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel1)
                        .add(jTxtFldMainDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jBtnMainDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTxtFldSecDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBtnSecDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jBtnLoad)
                        .add(jBtnSynch))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jChkBoxHideEquals)
                        .add(jChkBoxUseHash)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }//GEN-END:initComponents

    private void jChkBxMenuItemIncSubdirsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jChkBxMenuItemIncSubdirsItemStateChanged
        if (!firstLoad) {
            load();
        }
    }//GEN-LAST:event_jChkBxMenuItemIncSubdirsItemStateChanged

    private void jChkBxMenuItemHideEqualsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jChkBxMenuItemHideEqualsStateChanged
        jChkBoxHideEquals.setSelected(jChkBxMenuItemHideEquals.isSelected());
    }//GEN-LAST:event_jChkBxMenuItemHideEqualsStateChanged

    private void jChkBxMenuItemUseHashItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jChkBxMenuItemUseHashItemStateChanged
        jChkBoxUseHash.setSelected(jChkBxMenuItemUseHash.isSelected());
    }//GEN-LAST:event_jChkBxMenuItemUseHashItemStateChanged

    private void jMenuItemNewerInSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewerInSecActionPerformed
        selectFilesByStatus(FilePair.SEC_NEWER);
    }//GEN-LAST:event_jMenuItemNewerInSecActionPerformed

    private void jMenuItemNewerInMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewerInMainActionPerformed
        selectFilesByStatus(FilePair.MAIN_NEWER);
    }//GEN-LAST:event_jMenuItemNewerInMainActionPerformed

    private void jMenuItemOnlyInSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOnlyInSecActionPerformed
        selectFilesByStatus(FilePair.ONLY_SEC);
    }//GEN-LAST:event_jMenuItemOnlyInSecActionPerformed

    private void jMenuItemOnlyInMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOnlyInMainActionPerformed
        selectFilesByStatus(FilePair.ONLY_MAIN);
    }//GEN-LAST:event_jMenuItemOnlyInMainActionPerformed
    
    private void jMenuItemYesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemYesNoActionPerformed
        selectFilesByStatus(new short[] {FilePair.ONLY_MAIN, FilePair.ONLY_SEC});
    }//GEN-LAST:event_jMenuItemYesNoActionPerformed
    
    private void jMenuItemNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNoneActionPerformed
        selectAllFiles(false);
    }//GEN-LAST:event_jMenuItemNoneActionPerformed
    
    private void jMenuItemAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAllActionPerformed
        selectAllFiles(true);
    }//GEN-LAST:event_jMenuItemAllActionPerformed
    
    private void jMenuItemDirSynchHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDirSynchHelpActionPerformed
        String helpText;
        try {
            helpText = FileUtil.readFile(helpFile);
            jEdtPaneHelp.setText(helpText);
            jEdtPaneHelp.setCaretPosition(0);
            jDialogHelp.pack();
            jDialogHelp.setVisible(true);
        } catch (IOException ex) {
            MainJFrame.log(ex);
        }
    }//GEN-LAST:event_jMenuItemDirSynchHelpActionPerformed
    
    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        showAbout();
    }//GEN-LAST:event_jMenuItemAboutActionPerformed
    
    private void jChkBoxUseHashItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jChkBoxUseHashItemStateChanged
        jChkBxMenuItemUseHash.setSelected(jChkBoxUseHash.isSelected());
        if (!firstLoad) {
            load();
        }
    }//GEN-LAST:event_jChkBoxUseHashItemStateChanged
    
    private void jChkBoxHideEqualsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jChkBoxHideEqualsItemStateChanged
        jChkBxMenuItemHideEquals.setSelected(jChkBoxHideEquals.isSelected());
        if (!firstLoad) {
            load();
        }
    }//GEN-LAST:event_jChkBoxHideEqualsItemStateChanged
    
    private void jTxtFldSecDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFldSecDirKeyTyped
        jBtnSynch.setEnabled(false);
        firstLoad = true;
    }//GEN-LAST:event_jTxtFldSecDirKeyTyped
    
    private void jTxtFldMainDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFldMainDirKeyTyped
        jBtnSynch.setEnabled(false);
        firstLoad = true;
    }//GEN-LAST:event_jTxtFldMainDirKeyTyped
    
    private void jBtnSynchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSynchActionPerformed
        synchronize();
    }//GEN-LAST:event_jBtnSynchActionPerformed
    
    private void jBtnSecDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSecDirActionPerformed
        selectDir(evt);
    }//GEN-LAST:event_jBtnSecDirActionPerformed
    
    private void jBtnMainDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMainDirActionPerformed
        selectDir(evt);
    }//GEN-LAST:event_jBtnMainDirActionPerformed
    
    private void statusBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusBarMouseClicked
        showAbout();
    }//GEN-LAST:event_statusBarMouseClicked
    
    private void jBtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoadActionPerformed
        load();
    }//GEN-LAST:event_jBtnLoadActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        processParams(args);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    private static boolean processParams(String[] args) {
        boolean continueAfterThis = true;
        try {
            for (int i = 0; i < args.length; i++) {
                if ("-main".equals(args[i])) {
                    defaultMainDirPath = args[++i];
                } else if ("-sec".equals(args[i])) {
                    defaultSecDirPath = args[++i];
                } else if ("-help".equals(args[i])) {
                    showUsage();
                    continueAfterThis = false;
                } else if ("-keep".equals(args[i])) {
                    defaultKeep = true;
                }
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Incorrect parameters!");
            showUsage();
            continueAfterThis = false;
        }
        return continueAfterThis;
    }
    
    private static void showUsage() {
        System.out.println("DirSynch "+version+"\n© 2006 Itamar Carvalho <itamarc at gmail.com>\n");
        System.out.println("java[w] -jar DirSynch.jar <Params>");
        System.out.println("Params:");
        System.out.println("  -main <main dir path>  Set the main dir.");
        System.out.println("  -sec <sec dir path>    Set the secondary dir.");
        System.out.println("  -help                  Show this usage message.");
        System.out.println("  -keep                  Keep backups.");
    }
    
    private void selectDir(ActionEvent evt) {
        JButton button = (JButton)evt.getSource();
        String buttonName = button.getName();
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if ("jBtnMainDir".equals(buttonName)) {
            chooser.setCurrentDirectory(new File(getMainDirPath()));
        } else {
            chooser.setCurrentDirectory(new File(getSecDirPath()));
        }
        //DirFileFilter filter = new DirFileFilter();
        //chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            if ("jBtnMainDir".equals(buttonName)) {
                setMainDirPath(chooser.getSelectedFile().getAbsolutePath());
            } else { // jBtnSecDir
                setSecDirPath(chooser.getSelectedFile().getAbsolutePath());
            }
        }
        jBtnSynch.setEnabled(false);
        firstLoad = true;
    }
    
    private boolean dirsOk() {
        mainDir = new File(getMainDirPath());
        if (!mainDir.isDirectory() || !mainDir.canRead()) {
            JOptionPane.showMessageDialog(this,
                    "Directory '" + mainDir + "' does not exist or can't be read.\nCheck the paths!",
                    "Warning!",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            secDir = new File(getSecDirPath());
            if (!secDir.isDirectory() || !secDir.canRead()) {
                JOptionPane.showMessageDialog(this,
                        "Directory '" + secDir + "' does not exist or can't be read.\nCheck the paths!",
                        "Warning!",
                        JOptionPane.WARNING_MESSAGE);
                return false;
            } else {
                return true;
            }
        }
    }
    
    private String getMainDirPath() {
        return jTxtFldMainDir.getText();
    }
    private void setMainDirPath(String path) {
        jTxtFldMainDir.setText(path);
    }
    
    private String getSecDirPath() {
        return jTxtFldSecDir.getText();
    }
    private void setSecDirPath(String path) {
        jTxtFldSecDir.setText(path);
    }
    
    private void compareDirs()
    throws IOException, NoSuchAlgorithmException {
        final MainJFrame mainFrame = this;
        Runnable syncRun = new Runnable() {
            public void run() {
                int step = 0;
                ProgressMonitor progressMonitor = null;
                try {
                    setButtonsEnabled(false, false);
                    progressMonitor = new ProgressMonitor(mainFrame,
                            "Loading . . .",
                            "", 0, 6);
                    progressMonitor.setMillisToDecideToPopup(0);
                    progressMonitor.setMillisToPopup(0);
                    progressMonitor.setNote("Loading no synch files");
                    // Step 1 - Loading no synch files
                    loadNoSynchFiles();
                    if (progressMonitor.isCanceled()) {
                        throw new InterruptedException();
                    }
                    progressMonitor.setNote("Loading main dir data");
                    progressMonitor.setProgress(++step);
                    // Step 2 - Loading main dir data
                    mainDirMap = new HashMap();
                    buildMap(mainDir, mainDirMap, mainDir.getPath().length());
                    if (progressMonitor.isCanceled()) {
                        throw new InterruptedException();
                    }
                    progressMonitor.setNote("Loading sec dir data");
                    progressMonitor.setProgress(++step);
                    // Step 3 - Loading sec dir data
                    secDirMap = new HashMap();
                    buildMap(secDir, secDirMap, secDir.getPath().length());
                    if (progressMonitor.isCanceled()) {
                        throw new InterruptedException();
                    }
                    progressMonitor.setNote("Comparing data");
                    progressMonitor.setProgress(++step);
                    // Step 4 - Comparing data
                    // Compare maps
                    Vector files = new Vector(mainDirMap.size());
                    // Main
                    Iterator iter = mainDirMap.keySet().iterator();
                    FilePair file;
                    while (iter.hasNext()) {
                        if (progressMonitor.isCanceled()) {
                            throw new InterruptedException();
                        }
                        file = new FilePair((String)iter.next(), mainDir, secDir);
                        file.setUseHash(jChkBoxUseHash.isSelected());
                        file.setMainFile((File)mainDirMap.get(file.getPath()));
                        //System.out.println("File added: '"+file.getPath()+"'");
                        if (secDirMap.containsKey(file.getPath())) {
                            file.setSecFile((File)secDirMap.get(file.getPath()));
                        }
                        files.add(file);
                    }
                    // Sec
                    iter = secDirMap.keySet().iterator();
                    while (iter.hasNext()) {
                        if (progressMonitor.isCanceled()) {
                            throw new InterruptedException();
                        }
                        String path = (String)iter.next();
                        if (!mainDirMap.containsKey(path)) {
                            file = new FilePair(path, mainDir, secDir);
                            file.setUseHash(jChkBoxUseHash.isSelected());
                            file.setSecFile((File)secDirMap.get(file.getPath()));
                            files.add(file);
                        }
                    }
                    // Show differences
                    if (progressMonitor.isCanceled()) {
                        throw new InterruptedException();
                    }
                    progressMonitor.setNote("Sorting data");
                    progressMonitor.setProgress(++step);
                    // Step 5 - Sorting data
                    Collections.sort(files);
                    if (progressMonitor.isCanceled()) {
                        throw new InterruptedException();
                    }
                    progressMonitor.setNote("Preparing to show data");
                    progressMonitor.setProgress(++step);
                    // Step 6 - Preparing to show data
                    ((FileVOTableModel)jTableFiles.getModel()).setFiles(files, getHideEquals());
                    progressMonitor.setProgress(++step);
                    progressMonitor.close();
                    setButtonsEnabled(true, true);
                } catch (InterruptedException ex) {
                    JOptionPane.showMessageDialog(mainFrame,
                            "Loading operation CANCELED!", "Cancelled",
                            JOptionPane.WARNING_MESSAGE);
                    setButtonsEnabled(true, false);
                    if (progressMonitor != null) {
                        progressMonitor.close();
                    }
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(mainFrame,
                            ex.getClass().getName() + ": " + ex.getMessage(),
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                    MainJFrame.log(ex);
                    setButtonsEnabled(true, false);
                } catch (NoSuchAlgorithmException ex) {
                    JOptionPane.showMessageDialog(mainFrame,
                            ex.getClass().getName() + ": " + ex.getMessage(),
                            "Weird Error!",
                            JOptionPane.ERROR_MESSAGE);
                    MainJFrame.log(ex);
                    setButtonsEnabled(true, false);
                }
            }
        };
        new Thread(syncRun).start();
    }
    
    private boolean getHideEquals() {
        return jChkBoxHideEquals.isSelected();
    }
    
    private void loadNoSynchFiles() {
        File[] noSynchFiles = {
            new File(mainDir + File.separator + ".nosynch"),
            new File(mainDir + File.separator + "_nosynch"),
            new File(secDir + File.separator + ".nosynch"),
            new File(secDir + File.separator + "_nosynch"),
            new File(System.getProperty("user.dir") + File.separator + ".nosynch"),
            new File(System.getProperty("user.dir") + File.separator + "_nosynch")
        };
        noSynchMap = new HashMap();
        for (int i = 0; i < noSynchFiles.length; i++) {
            if (noSynchFiles[i].isFile() && noSynchFiles[i].canRead()) {
//		System.out.println("File found: "+noSynchFiles[i]);
                loadNoSynchFile(noSynchFiles[i]);
//	    } else {
//		System.out.println("File not found: "+noSynchFiles[i]);
            }
        }
    }
    
    private Map getNoSynchMap() {
        if (noSynchMap == null) {
            noSynchMap = new HashMap();
        }
        return noSynchMap;
    }
    
    private void loadNoSynchFile(File noSynchFile) {
        Map map = getNoSynchMap();
        try {
            String[] lines = FileUtil.readFileAsArray(noSynchFile);
            for (int i = 0; i < lines.length; i++) {
                while (lines[i].endsWith("\r") || lines[i].endsWith("\n")) {
                    lines[i] = lines[i].substring(0, lines[i].length()-1);
                }
                if (lines[i] != null && !"".equals(lines[i])) {
                    map.put(lines[i], "1");
                }
            }
        } catch (IOException e) {
            MainJFrame.log("Failed to load file '"+noSynchFile+"'.");
            MainJFrame.log(e);
        }
    }
    
    private void buildMap(File dir, Map dirMap, int rootPathSize)
    throws IOException {
        File[] dirFiles = dir.listFiles();
        for (int i = 0; i < dirFiles.length; i++) {
            File file = dirFiles[i];
            if (!noSynchMap.containsKey(file.getName())) {
                if (file.isDirectory()) {
                    if (isIncludeSubdirs()) {
                        buildMap(file, dirMap, rootPathSize);
                    }
                } else {
                    dirMap.put(file.getPath().substring(rootPathSize), file);
                }
            }
        }
    }
    
    
    
    private void synchronize() {
        final MainJFrame mainFrame = this;
        Runnable syncRun = new Runnable() {
            public void run() {
                FilePair filePair = null;
                try {
                    setButtonsEnabled(false, false);
                    Vector files = ((FileVOTableModel)jTableFiles.getModel()).getFiles();
                    ProgressMonitor progressMonitor = new ProgressMonitor(mainFrame,
                            "Synchronizing . . .",
                            "", 0, files.size());
                    progressMonitor.setMillisToDecideToPopup(0);
                    progressMonitor.setMillisToPopup(0);
                    boolean cancel = false;
                    for (int i = 0; i < files.size(); i++) {
                        if (progressMonitor.isCanceled()) {
                            cancel = true;
                            break;
                        }
                        jTableFiles.setRowSelectionInterval(i, i);
                        Boolean selected = (Boolean)jTableFiles.getModel().getValueAt(i, 0);
                        if (selected) {
                            filePair = (FilePair)files.get(i);
                            progressMonitor.setNote(filePair.getPath());
                            filePair.synchronize(jChkBxMenuItemKeepBackup.isSelected());
                        }
                        progressMonitor.setProgress(i);
                    }
                    progressMonitor.close();
                    if (cancel) {
                        JOptionPane.showMessageDialog(mainFrame,
                                "Synchronization CANCELED!", "Cancelled",
                                JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(mainFrame,
                                "Synchronization completed!", "Success",
                                JOptionPane.INFORMATION_MESSAGE);
                    }
                    load();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(mainFrame,
                            "Failure in synchronization process!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    MainJFrame.log("Error processing file: " + filePair);
                    MainJFrame.log(ex);
                } finally {
                    setButtonsEnabled(true, true);
                }
            }
        };
        new Thread(syncRun).start();
    }
    void setButtonsEnabled(boolean loadStatus, boolean synchStatus) {
        jBtnLoad.setEnabled(loadStatus);
        jChkBoxHideEquals.setEnabled(loadStatus);
//        jChkBoxKeepBackup.setEnabled(loadStatus);
        jChkBoxUseHash.setEnabled(loadStatus);
        jTxtFldMainDir.setEnabled(loadStatus);
        jTxtFldSecDir.setEnabled(loadStatus);
        jBtnMainDir.setEnabled(loadStatus);
        jBtnSecDir.setEnabled(loadStatus);
        jBtnSynch.setEnabled(synchStatus);
    }
    
    private void load() {
        if (dirsOk()) {
            try {
                compareDirs();
                firstLoad = false;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getClass().getName() + ": " + ex.getMessage(),
                        "I/O Error!",
                        JOptionPane.ERROR_MESSAGE);
                MainJFrame.log(ex);
            } catch (NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getClass().getName() + ": " + ex.getMessage(),
                        "Weird Error!",
                        JOptionPane.ERROR_MESSAGE);
                MainJFrame.log(ex);
            }
        }
    }
    
    private void setStatusBarText(String text) {
        jLblStatusBar.setText(text);
    }
    
    private void updateStatus() {
        setStatusBarText(getSelectedFilePair().getStatus());
    }
    
    private FilePair getSelectedFilePair() {
        FileVOTableModel model = ((FileVOTableModel)jTableFiles.getModel());
        int row = jTableFiles.getSelectedRow();
        return ( row >= 0 ? (FilePair) model.getFiles().get(row) : null );
    }
    
    private void showAbout() {
        JOptionPane.showMessageDialog(this,
                "DirSynch "+version+"\n© 2007 Itamar Carvalho <itamarc at gmail.com>",
                "About DirSynch",
                JOptionPane.INFORMATION_MESSAGE);
    }
    
    public static void log(String message) {
        System.err.println(new Date().toString() + message);
        System.err.flush();
    }
    public static void log(Exception ex) {
        System.err.println(new Date().toString());
        ex.printStackTrace(System.err);
        System.err.flush();
    }
    
    private void selectAllFiles(boolean checked) {
        // If the action is to uncheck all or if the "hide equals" option is on, do all
        if (!checked || getHideEquals()) {
            for (int i = 0; i < ((FileVOTableModel)jTableFiles.getModel()).getRowCount(); i++) {
                jTableFiles.getModel().setValueAt(new Boolean(checked), i, 0);
            }
        } else {  // Select only the different files
            Vector files = ((FileVOTableModel)jTableFiles.getModel()).getFiles();
            for (int i = 0; i < files.size(); i++) {
                if (!((FilePair)files.get(i)).isEquals()) {
                    jTableFiles.getModel().setValueAt(new Boolean(checked), i, 0);
                }
            }
        }
    }
    
    private void selectFilesByStatus(short status) {
        selectFilesByStatus(new short[] {status});
    }
    
    private void selectFilesByStatus(short[] statusList) {
        // If the action is to uncheck all or if the "hide equals" option is on, do all
        Vector files = ((FileVOTableModel)jTableFiles.getModel()).getFiles();
        for (int i = 0; i < files.size(); i++) {
            // If the status of the pair is in the list received
            if (statusInList(((FilePair)files.get(i)).getNewer(), statusList)) {
                jTableFiles.getModel().setValueAt(true, i, 0);
            } else {
                jTableFiles.getModel().setValueAt(false, i, 0);
            }
        }
    }
    
    private boolean statusInList(short status, short[] statusList) {
        boolean found = false;
        for (int i = 0; i < statusList.length; i++) {
            if (status == statusList[i]) {
                found = true;
            }
        }
        return found;
    }

    private boolean isIncludeSubdirs() {
        return jChkBxMenuItemIncSubdirs.isSelected();
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoad;
    private javax.swing.JButton jBtnMainDir;
    private javax.swing.JButton jBtnSecDir;
    private javax.swing.JButton jBtnSynch;
    private javax.swing.JCheckBox jChkBoxHideEquals;
    private javax.swing.JCheckBox jChkBoxUseHash;
    private javax.swing.JCheckBoxMenuItem jChkBxMenuItemHideEquals;
    private javax.swing.JCheckBoxMenuItem jChkBxMenuItemIncSubdirs;
    private javax.swing.JCheckBoxMenuItem jChkBxMenuItemKeepBackup;
    private javax.swing.JCheckBoxMenuItem jChkBxMenuItemUseHash;
    private javax.swing.JDialog jDialogHelp;
    private javax.swing.JEditorPane jEdtPaneHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblStatusBar;
    private javax.swing.JMenuBar jMenuBarDirSynch;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemAll;
    private javax.swing.JMenuItem jMenuItemDirSynchHelp;
    private javax.swing.JMenuItem jMenuItemNewerInMain;
    private javax.swing.JMenuItem jMenuItemNewerInSec;
    private javax.swing.JMenuItem jMenuItemNone;
    private javax.swing.JMenuItem jMenuItemOnlyInMain;
    private javax.swing.JMenuItem jMenuItemOnlyInSec;
    private javax.swing.JMenuItem jMenuItemYesNo;
    private javax.swing.JMenu jMenuOptions;
    private javax.swing.JMenu jMenuSelect;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneHelp;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableFiles;
    private javax.swing.JTextField jTxtFldMainDir;
    private javax.swing.JTextField jTxtFldSecDir;
    private javax.swing.JPanel statusBar;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
