/*
 * MainJFrame.java
 *
 * Created on 3 de Agosto de 2006, 20:32
 */

package itamar.dirsynch;

import com.oktiva.util.FileUtil;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author  Itamar
 */
public class MainJFrame extends javax.swing.JFrame {
    private File mainDir;
    private File secDir;
    private Map mainDirMap;
    private Map secDirMap;
    private static String defaultMainDirPath = "D:\\home\\itamar\\pessoal\\SCEA";
    private static String defaultSecDirPath = "H:\\SCEA";
    private static String version = "1.1";
    private static boolean defaultKeep = false;
    private Map noSynchMap = null;
    
    /** Creates new form MainJFrame */
    public MainJFrame() {
	initComponents();
	
	jTableFiles.getColumn("Sel").setMaxWidth(30);
	jTableFiles.getColumn("Main").setMaxWidth(30);
	jTableFiles.getColumn("Sec").setMaxWidth(30);
	setStatusBarText(FilePair.getLegend());
	
	jTxtFldMainDir.setText(defaultMainDirPath);
	jTxtFldSecDir.setText(defaultSecDirPath);
	jChkBoxKeepBackup.setSelected(defaultKeep);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtFldSecDir = new javax.swing.JTextField();
        jTxtFldMainDir = new javax.swing.JTextField();
        statusBar = new javax.swing.JPanel();
        jLblStatusBar = new javax.swing.JLabel();
        jBtnMainDir = new javax.swing.JButton();
        jBtnSecDir = new javax.swing.JButton();
        jBtnLoad = new javax.swing.JButton();
        jBtnSynch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFiles = new javax.swing.JTable();
        jChkBoxKeepBackup = new javax.swing.JCheckBox();
        jChkBoxHideEquals = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DirSync");
        jLabel1.setText("Main directory:");

        jLabel2.setText("Second directory:");

        jTxtFldSecDir.setText("H:\\SCEA");
        jTxtFldSecDir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 128, 0)));
        jTxtFldSecDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFldSecDirKeyTyped(evt);
            }
        });

        jTxtFldMainDir.setText("D:\\home\\itamar\\pessoal\\SCEA");
        jTxtFldMainDir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jTxtFldMainDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFldMainDirKeyTyped(evt);
            }
        });

        statusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        statusBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusBarMouseClicked(evt);
            }
        });

        jLblStatusBar.setText(" ");

        org.jdesktop.layout.GroupLayout statusBarLayout = new org.jdesktop.layout.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusBarLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLblStatusBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLblStatusBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jBtnMainDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dir.png")));
        jBtnMainDir.setToolTipText("Select main dir...");
        jBtnMainDir.setIconTextGap(0);
        jBtnMainDir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBtnMainDir.setMinimumSize(new java.awt.Dimension(20, 20));
        jBtnMainDir.setName("jBtnMainDir");
        jBtnMainDir.setPreferredSize(new java.awt.Dimension(20, 20));
        jBtnMainDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMainDirActionPerformed(evt);
            }
        });

        jBtnSecDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dir.png")));
        jBtnSecDir.setToolTipText("Select second dir...");
        jBtnSecDir.setIconTextGap(0);
        jBtnSecDir.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBtnSecDir.setMinimumSize(new java.awt.Dimension(20, 20));
        jBtnSecDir.setName("jBtnSecDir");
        jBtnSecDir.setPreferredSize(new java.awt.Dimension(20, 20));
        jBtnSecDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSecDirActionPerformed(evt);
            }
        });

        jBtnLoad.setText("Load");
        jBtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoadActionPerformed(evt);
            }
        });

        jBtnSynch.setText("Synchronize");
        jBtnSynch.setEnabled(false);
        jBtnSynch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSynchActionPerformed(evt);
            }
        });

        jTableFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableFiles.setModel(new FileVOTableModel(
            new Object [][] {
                {new Boolean(false), null, null, null}
            },
            new String [] {
                "Sel", "Main", "Sec", "File"
            }
        ));
        jTableFiles.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTableFiles);

        jChkBoxKeepBackup.setText("Keep backup");
        jChkBoxKeepBackup.setToolTipText("Check to keep backup of the overwritten files.");
        jChkBoxKeepBackup.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChkBoxKeepBackup.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jChkBoxHideEquals.setText("Hide equals");
        jChkBoxHideEquals.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jChkBoxHideEquals.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jChkBoxHideEquals.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jChkBoxHideEqualsItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jTxtFldMainDir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jBtnMainDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jTxtFldSecDir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jBtnSecDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(statusBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jBtnLoad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnSynch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 102, Short.MAX_VALUE)
                        .add(jChkBoxHideEquals)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jChkBoxKeepBackup)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel1)
                        .add(jTxtFldMainDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jBtnMainDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTxtFldSecDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBtnSecDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jBtnLoad)
                        .add(jBtnSynch))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jChkBoxKeepBackup)
                        .add(jChkBoxHideEquals)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jChkBoxHideEqualsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jChkBoxHideEqualsItemStateChanged
	load();
    }//GEN-LAST:event_jChkBoxHideEqualsItemStateChanged
    
    private void jTxtFldSecDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFldSecDirKeyTyped
	jBtnSynch.setEnabled(false);
    }//GEN-LAST:event_jTxtFldSecDirKeyTyped
    
    private void jTxtFldMainDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFldMainDirKeyTyped
	jBtnSynch.setEnabled(false);
    }//GEN-LAST:event_jTxtFldMainDirKeyTyped
    
    private void jBtnSynchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSynchActionPerformed
	synchronize();
    }//GEN-LAST:event_jBtnSynchActionPerformed
    
    private void jBtnSecDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSecDirActionPerformed
	selectDir(evt);
    }//GEN-LAST:event_jBtnSecDirActionPerformed
    
    private void jBtnMainDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMainDirActionPerformed
	selectDir(evt);
    }//GEN-LAST:event_jBtnMainDirActionPerformed
    
    private void statusBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusBarMouseClicked
	JOptionPane.showMessageDialog(this,
		"DirSynch "+version+"\n© 2006 Itamar Carvalho <itamarc at gmail.com>",
		"About DirSynch",
		JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_statusBarMouseClicked
    
    private void jBtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoadActionPerformed
	load();
    }//GEN-LAST:event_jBtnLoadActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	processParams(args);
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new MainJFrame().setVisible(true);
	    }
	});
    }
    
    private static boolean processParams(String[] args) {
	boolean continueAfterThis = true;
	try {
	    for (int i = 0; i < args.length; i++) {
		if ("-main".equals(args[i])) {
		    defaultMainDirPath = args[++i];
		} else if ("-sec".equals(args[i])) {
		    defaultSecDirPath = args[++i];
		} else if ("-help".equals(args[i])) {
		    showUsage();
		    continueAfterThis = false;
		} else if ("-keep".equals(args[i])) {
		    defaultKeep = true;
		}
	    }
	} catch (ArrayIndexOutOfBoundsException e) {
	    System.out.println("Incorrect parameters!");
	    showUsage();
	    continueAfterThis = false;
	}
	return continueAfterThis;
    }
    
    private static void showUsage() {
	System.out.println("DirSynch "+version+"\n© 2006 Itamar Carvalho <itamarc at gmail.com>\n");
	System.out.println("java[w] -jar DirSynch.jar <options>");
	System.out.println("Params:");
	System.out.println("  -main <main dir path>  Set the main dir.");
	System.out.println("  -sec <sec dir path>    Set the secondary dir.");
	System.out.println("  -help                  Show this usage message.");
	System.out.println("  -keep                  Keep backups.");
    }
    
    private void selectDir(ActionEvent evt) {
	JButton button = (JButton)evt.getSource();
	String buttonName = button.getName();
	JFileChooser chooser = new JFileChooser();
	chooser.setAcceptAllFileFilterUsed(false);
	chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
	if ("jBtnMainDir".equals(buttonName)) {
	    chooser.setCurrentDirectory(new File(getMainDirPath()));
	} else {
	    chooser.setCurrentDirectory(new File(getSecDirPath()));
	}
	//DirFileFilter filter = new DirFileFilter();
	//chooser.setFileFilter(filter);
	int returnVal = chooser.showOpenDialog(this);
	if(returnVal == JFileChooser.APPROVE_OPTION) {
	    if ("jBtnMainDir".equals(buttonName)) {
		setMainDirPath(chooser.getSelectedFile().getAbsolutePath());
	    } else { // jBtnSecDir
		setSecDirPath(chooser.getSelectedFile().getAbsolutePath());
	    }
	}
	jBtnSynch.setEnabled(false);
    }
    
    private boolean dirsOk() {
	mainDir = new File(getMainDirPath());
	if (!mainDir.isDirectory() || !mainDir.canRead()) {
	    JOptionPane.showMessageDialog(this,
		    "Directory '" + mainDir + "' does not exist or can't be read.\nCheck the paths!",
		    "Warning!",
		    JOptionPane.WARNING_MESSAGE);
	    return false;
	} else {
	    secDir = new File(getSecDirPath());
	    if (!secDir.isDirectory() || !secDir.canRead()) {
		JOptionPane.showMessageDialog(this,
			"Directory '" + secDir + "' does not exist or can't be read.\nCheck the paths!",
			"Warning!",
			JOptionPane.WARNING_MESSAGE);
		return false;
	    } else {
		return true;
	    }
	}
    }
    
    private String getMainDirPath() {
	return jTxtFldMainDir.getText();
    }
    private void setMainDirPath(String path) {
	jTxtFldMainDir.setText(path);
    }
    
    private String getSecDirPath() {
	return jTxtFldSecDir.getText();
    }
    private void setSecDirPath(String path) {
	jTxtFldSecDir.setText(path);
    }
    
    private void compareDirs()
    throws IOException {
	loadNoSynchFiles();
	mainDirMap = new HashMap();
	buildMap(mainDir, mainDirMap, mainDir.getPath().length());
	secDirMap = new HashMap();
	buildMap(secDir, secDirMap, secDir.getPath().length());
	// Compare maps
	Vector files = new Vector(mainDirMap.size());
	// Main
	Iterator iter = mainDirMap.keySet().iterator();
	FilePair file;
	while (iter.hasNext()) {
	    file = new FilePair((String)iter.next(), mainDir, secDir);
	    file.setMainFile((File)mainDirMap.get(file.getPath()));
	    //System.out.println("File added: '"+file.getPath()+"'");
	    if (secDirMap.containsKey(file.getPath())) {
		//System.out.println("Sec file found: '"+file.getPath()+"'");
		file.setSecFile((File)secDirMap.get(file.getPath()));
	    }
	    files.add(file);
	}
	// Sec
	iter = secDirMap.keySet().iterator();
	while (iter.hasNext()) {
	    String path = (String)iter.next();
	    if (!mainDirMap.containsKey(path)) {
		file = new FilePair(path, mainDir, secDir);
		file.setSecFile((File)secDirMap.get(file.getPath()));
		files.add(file);
		//System.out.println("File sec created: '"+file.getPath()+"'");
		//} else {
		//System.out.println("File already found: '"+path+"'");
	    }
	}
	//System.out.println("Files vector:\n" + files);
	// Show differences
	Collections.sort(files);
	((FileVOTableModel)jTableFiles.getModel()).setFiles(files, jChkBoxHideEquals.isSelected());
    }
    
    private void loadNoSynchFiles() {
	File[] noSynchFiles = {
	    new File(mainDir + File.separator + ".nosynch"),
	    new File(mainDir + File.separator + "_nosynch"),
	    new File(secDir + File.separator + ".nosynch"),
	    new File(secDir + File.separator + "_nosynch"),
	    new File(System.getProperty("user.dir") + File.separator + ".nosynch"),
	    new File(System.getProperty("user.dir") + File.separator + "_nosynch")
	};
	noSynchMap = new HashMap();
	for (int i = 0; i < noSynchFiles.length; i++) {
	    if (noSynchFiles[i].isFile() && noSynchFiles[i].canRead()) {
//		System.out.println("File found: "+noSynchFiles[i]);
		loadNoSynchFile(noSynchFiles[i]);
//	    } else {
//		System.out.println("File not found: "+noSynchFiles[i]);
	    }
	}
    }
    
    private Map getNoSynchMap() {
	if (noSynchMap == null) {
	    noSynchMap = new HashMap();
	}
	return noSynchMap;
    }
    
    private void loadNoSynchFile(File noSynchFile) {
	Map map = getNoSynchMap();
	try {
	    String[] lines = FileUtil.readFileAsArray(noSynchFile);
	    for (int i = 0; i < lines.length; i++) {
		while (lines[i].endsWith("\r") || lines[i].endsWith("\n")) {
		    lines[i] = lines[i].substring(0, lines[i].length()-1);
		}
		if (lines[i] != null && !"".equals(lines[i])) {
		    map.put(lines[i], "1");
		}
	    }
	} catch (IOException e) {
	    System.err.println("Failed to load file '"+noSynchFile+"'.");
	    e.printStackTrace(System.err);
	}
    }
    
    private void buildMap(File dir, Map dirMap, int rootPathSize)
    throws IOException {
	File[] dirFiles = dir.listFiles();
	for (int i = 0; i < dirFiles.length; i++) {
	    File file = dirFiles[i];
	    if (!noSynchMap.containsKey(file.getName())) {
		if (file.isDirectory()) {
		    buildMap(file, dirMap, rootPathSize);
		} else {
		    dirMap.put(file.getPath().substring(rootPathSize), file);
		}
	    }
	}
//	System.out.println("Dir: " + dir.getPath());
//	System.out.println("Map: " + dirMap);
//	System.out.println("Map size: " + dirMap.size());
    }
    
    private void synchronize() {
	try {
	    Vector files = ((FileVOTableModel)jTableFiles.getModel()).getFiles();
	    for (int i = 0; i < files.size(); i++) {
		jTableFiles.setRowSelectionInterval(i, i);
		Boolean selected = (Boolean)jTableFiles.getModel().getValueAt(i, 0);
		if (selected) {
		    FilePair filePair = (FilePair)files.get(i);
		    filePair.synchronize(jChkBoxKeepBackup.isSelected());
		}
	    }
	    JOptionPane.showMessageDialog(this,
		    "Synchronization completed!", "Success",
		    JOptionPane.INFORMATION_MESSAGE);
	    load();
	} catch (IOException ex) {
	    JOptionPane.showMessageDialog(this,
		    "Failure in synchronization process!",
		    "Error",
		    JOptionPane.ERROR_MESSAGE);
	    ex.printStackTrace();
	}
    }
    
    private void load() {
	if (dirsOk()) {
	    try {
		compareDirs();
		jBtnSynch.setEnabled(true);
	    } catch (IOException ex) {
		JOptionPane.showMessageDialog(this,
			ex.getClass().getName() + ": " + ex.getMessage(),
			"Error!",
			JOptionPane.ERROR_MESSAGE);
	    }
	}
    }
    
    private void setStatusBarText(String text) {
	jLblStatusBar.setText(text);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoad;
    private javax.swing.JButton jBtnMainDir;
    private javax.swing.JButton jBtnSecDir;
    private javax.swing.JButton jBtnSynch;
    private javax.swing.JCheckBox jChkBoxHideEquals;
    private javax.swing.JCheckBox jChkBoxKeepBackup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblStatusBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFiles;
    private javax.swing.JTextField jTxtFldMainDir;
    private javax.swing.JTextField jTxtFldSecDir;
    private javax.swing.JPanel statusBar;
    // End of variables declaration//GEN-END:variables
    
}
