name: Page generation from templates

on:
  # Trigger on page_build, as well as release created events
  page_build:
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  update-docs-on-gh-pages-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1
        env:
          # The branch where the files will be copied from
          key: master
          # The destination branch
          branches: gh-pages
          # The files that will be copied
          files: README.md www/DirSynch-help.html
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # The branch where the templates are stored
        # (if not present, uses the 'master' branch)
        # (recomended: use the same branch configured to be used in GH Pages)
        ref: 'gh-pages'
    - uses: itamarc/action-itemplate-ghpages@v1test
      with:
        # The relative path to the folder that contains your site's templates
        # or the identification of the theme you want to use (required)
        templates_folder: ':light:'
        # Allow the templates to be stored in subfolders under templates_folder (not required, default 'false').
        # The output folders tree will map the input.
        allow_templates_subfolders: 'false'
        # The relative path to the folder that contains your site's snippets, if any (not required)
        # If this is set and allow_templates_subfolders is true, can't be inside de templates tree.
        snippets_folder: 'snippets'
        # Branch name for storing github pages (required)
        pages_branch: 'gh-pages'
        # Name of the output folder where generated html will be stored (required)
        pages_folder: 'docs'
        # Time zone to calculate the update time (required)
        # (default: America/Sao_Paulo, which is GMT-3 - sorry, I'm brazilian =) )
        timezone: 'America/Sao_Paulo'
        # Publish the README.md from the repository root in the generated page as README.html (not required, default 'false')
        # The themes will automatically insert a link to the README.html file in the index.html file if this is 'true'.
        publish_readme_md: 'true'
        # Folders or files to copy when publishing, keeping the relative path, separated by commas (not required, default '' - meaning none).
        # These files will be copied to the output folder without any change.
        content_to_copy: 'www'
        # The log level, according to the ones defined in java.util.logging.Level. (not required, default 'WARNING')
        log_level: 'FINER'
      env:
        # Needed to publish the pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
